### ISSUE TITLE
JSONPath and JSONata

### ISSUE THREAD

**Issue by trungswat** [grafana/grafana-json-datasource#185]
Hi,

Thank you for your hard work, this plugin works pretty well now.

But I found something does not work well in query with a variable in both JSONpath and JSONata
Here is my problem:

- Using JSONPath:

**_$.DevInfo[?(@.Date=="$Date")].Projects[?(@.ProjectName =~ /.*Test/ )]_** --> not work with regex /.*Test/

- Using JSONata

**_$.DevInfo[?(@.Date=="$Date")].Projects[*].ProjectName_** --> work well

**_DevInfo[Date=$Date)].Projects.ProjectName_** --> not work 

Hope you could help me. Thank you in advance.

**Comment by u2mejc** [comment]
I've also seen oddities with the JSONPath implimentation, two I've run into:
- If root JSON object starts with `[`, filters don't work as expected
- the `in` filter doesn't seem to be working

For the later, here's an example:
object:
```
{
   "store" : {
      "book" : [
         {
            "category" : "reference",
            "author" : "Nigel Rees",
            "title" : "Sayings of the Century",
            "price" : 8.95
         },
         {
            "category" : "fiction",
            "author" : "Evelyn Waugh",
            "title" : "Sword of Honour",
            "price" : 12.99
         },
         {
            "category" : "fiction",
            "author" : "Herman Melville",
            "title" : "Moby Dick",
            "isbn" : "0-553-21311-3",
            "price" : 8.99
         },
         {
            "category" : "fiction",
            "author" : "J. R. R. Tolkien",
            "title" : "The Lord of the Rings",
            "isbn" : "0-395-19395-8",
            "price" : 22.99
         }
      ],
      "bicycle" : {
         "color" : "red",
         "price" : 19.95
      }
   },
   "expensive" : 10
}
```
JSONPath:
```
$.store.book[?(@.category in ['fiction', 'non-fiction'])].author
```
Expected result:
```
[
   "Evelyn Waugh",
   "Herman Melville",
   "J. R. R. Tolkien"
]
```

**Comment by tiebingzhang** [comment]
@u2mejc  For your query, the following works for me: 

```
store.book[category in ['fiction', 'non-fiction']].author
```

**Comment by Abuu001** [comment]
For me this does not work. is there a fix for this issue

**Comment by gabor** [comment]
hi, various problem reports got mixed up here, we got no feedback from the original author of the issue, so we'll close this issue. if you think your problem was not answered, please:
1. if you think you found a bug in how the json-plugin handles your jsonata/jsonpath scenario, please open a new issue.
2. if your problem is more about how to achieve something with jsonata/jsonpath, i recommend asking on the community forums at https://community.grafana.com/

thanks!
