### ISSUE TITLE
Fields "date" and "time" disappearing from data

### ISSUE THREAD

**Issue by ttftw** [grafana/grafana-json-datasource#195]
I have this example JSON structure:
```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "latitude": 37.0,
                "longitude": -90,
                "created_at": "2021-06-28 17:40:13 UTC",
                "site_name": "scrub",
                "date": "2021-06-28",
                "time": "12:40",
                "reason_for_visit": "Collect Data"
            }
        }
    ]
}
```
When I try to access the "date" or "time" fields, they do not show up in the auto complete nor function like they are actual fields in the data.

The query `$.features[*].properties.site_name` works fine to get the site_name field, but `$.features[*].properties.date` does not. When I use Grafana to look at the returned rows from `$.features[*].properties`, each row has a date field, but drilling down to `$.features[*].properties.date` doesn't seem to exist. 

Is there some reason these fields might be treated differently?

**Comment by marcusolsson** [comment]
I used the JSON data you provided (thanks for that!), but it seems to be working for me? 

<img width="1090" alt="Screenshot 2021-11-08 at 10 24 57@2x" src="https://user-images.githubusercontent.com/8396880/140716598-4d333638-5d16-4aea-b897-865de6204b0d.png">
