### ISSUE TITLE
Query is not executing based on selection of values from drop-down menu

### ISSUE THREAD

**Issue by satyamtpatel** [grafana/grafana-json-datasource#235]
Hi,

We are using JSON API plugin to fetch data from API. I added custom variable to fetch data from the API based on selection of value in dropdown. But when i select drop-down value, query is not executing. But when i go to param field and press tab key then it execute query. Can you please provide your assistance so that it fetch value based on selection of drop down?

Also, if query return no value then it is throwing "Cannot read property of undefined" error. Response from query are as below:

response:Object
count:0
total:4
list:Array[0]
[]

**Comment by marcusolsson** [comment]
If this is related to template variables, there are already a couple of issues related to this:

- https://github.com/marcusolsson/grafana-json-datasource/issues/155
- https://github.com/marcusolsson/grafana-json-datasource/issues/95

What version are you using? I think the "Cannot read property of undefined" have been fixed in 1.3.1.

**Comment by ideasman69** [comment]
Hi guys, I'm having the same problem with my dashboards... 

If I recall correctly - it seemed to happen just before Christmas with one of the log4j mitigation releases. 

My dashboards use a sql query to populate the variable dropdown. For any dashboards that use a combination of sql query and JSON panels, the sql panels update when the variable is changed. The JSON panels do not update unless the refresh button is manually clicked or page is fully refreshed.

**Comment by erlfos** [comment]
Hi
The data source is great, but this is a bit of a show stopper for us so I hope it gets fixed.
We are currently on Grafana 8.4.4 and use the same setup as ideasman69 describes (SQL to populate dropdown variable), and all panels update (using MySQL, InfluxDB and Prometheus data sources) except the ones using the JSON data source when we change the variable in the drop down menu. Clicking the refresh button in Grafana forces the JSON panels to update, but it is easy to forget.

**Comment by ideasman69** [comment]
Hi @erlfos, i have a feeling this was fixed! 

Yeah - looks like it was included in [8.5.0-beta1](https://github.com/grafana/grafana/pull/47049), but should be in every release since.

**Comment by erlfos** [comment]
Thanks for the info! I will try to upgrade to 8.5.

**Comment by sbowerscuttlesoft** [comment]
Hello, I am having this same issue with Grafana 9.2.2
I have a dashboard with a variable.  When I change the variable or the date range, my "timeseries" panel does not update.  I am checking in the console, and I do not see the call to my api happening when I change the value.
So, I added a "grafana" data source "random walk" to the same panel.  When I change variables, the random walk is updated, but my api is still not called

**Comment by gabor** [comment]
hi, is this problem still happening on grafana11 with the current json-plugin version (`1.3.15` at this point)?

**Comment by gabor** [comment]
as we got no new information, we're closing the issue. we can reopen it if we get new info.
