### ISSUE TITLE
Time shift doesn't work

### ISSUE THREAD

**Issue by danmx** [grafana/grafana-json-datasource#245]
I'm trying to display side by side data from two different time periods using time shift mechanism in [query options](https://grafana.com/docs/grafana/latest/panels/reference-query-options/#reference-query-options) and it seems it doesn't work for this data source (it works for Influxdb on the same dashboard).

I'm using an interval type variable to control the time shift.
I'm using Grafana `8.4.1` and JSON API data source version `1.3.1`.
Time window is sent using parameters and values are: `${__from:date:iso}` and `${__to:date:iso}`.

Changing to `$__to` and `$__from` doesn't make a difference nor using static value for time shift, e.g. `1d` instead of using a dashboard variable.

I checked the query both using Grafana's query inspector and at the data source service level.

**Comment by gabor** [comment]
hi @danmx , those two variables ( `__from` and `__to` ) represent the dashboard-level time-range, they do not get modified by a panel's time-shift. ( see https://github.com/grafana/grafana/issues/38954 ).

there are some variables, specific to this datasource plugin, that do respect the panel's time-shift (https://grafana.com/docs/plugins/marcusolsson-json-datasource/latest/macros/) , i recommend using `__isoFrom()` and `__isoTo()`.

i hope this helps.
