### ISSUE TITLE
Query returned empty data on 0 value

### ISSUE THREAD

**Issue by gschneller** [grafana/grafana-json-datasource#265]
### Discussed in https://github.com/marcusolsson/grafana-json-datasource/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **gschneller** March  2, 2022</sup>
Context:

- Grafana 8.3.2
- grafana_plugin marcusolsson-json-datasource-1.3.1.zip
- Panel: Stat

-Field: `$.`

My query retuned the json: 0
Query inspector return: 
```json
{
  "status": 200,
  "statusText": "",
  "ok": true,
  "data": 0,
  "url": "https://soc.itrust.fr/grafana/api/datasources/proxy/49/api/v1/query?name=case",
  "type": "basic",
  "redirected": false,
  "request": {
    "url": "api/datasources/proxy/49/api/v1/query?name=case",
    "method": "POST",
    "data": "{\n    \"query\": [\n        {\n        \"_name\": \"listCase\"\n        },\n        {\n        \"_name\": \"filter\",\n        \"_and\": [\n                {\n                    \"_between\": {\n                        \"_field\": \"_createdAt\",\n                        \"_from\": 1645628006921,\n                        \"_to\": 1646232806921\n                    }\n                },\n                {\n                    \"_field\": \"resolutionStatus\",\n                    \"_value\": \"Other\"\n                }\n            ]\n        },\n        {\n        \"_name\": \"count\"\n        }\n    ]\n}",
    "hideFromInspector": false
  }
}
```
And I have the error: `Query returned empty data` and display "N/A"

When my query return an integer > 0, All is OK

</div>

**Comment by marcusolsson** [comment]
`$.` doesn't look like a valid JSONPath. Could you provide the exact field query, and the (anonymized JSON) that produces the error?

**Comment by gabor** [comment]
as we received no response for a long time, we are closing the issue. we can reopen it if we receive new info.
