### ISSUE TITLE
id is invalid

### ISSUE THREAD

**Issue by anatoly-kor** [grafana/grafana-json-datasource#284]
Hi. I have a some issue. 
Environment: 
- API app in docker with network
- Grafana app in docker with same network

I try to get some value from api and get always 2 errors. 
1. "Bad Gateway" for `http://localhost/v1/`
2. "id is invalid"

For bad gateway I just add port (80) and its gone. But for id I always have the same traceback:
```{
  "request": {
    "url": "api/datasources/proxy/1/",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "message": "id is invalid",
    "traceID": "00000000000000000000000000000000"
  }
}
```

Totally confused. 

Thanks for your help

**Comment by AxelAli** [comment]
What i would do is to add the name for the docker service
like this
<img width="610" alt="Screen Shot 0004-07-22 at 16 18 27" src="https://user-images.githubusercontent.com/19843821/180510739-a337136c-e0df-48a0-9356-47c7f944525f.png">

**Comment by gabor** [comment]
hi @anatoly-kor , does the solution from https://github.com/grafana/grafana-json-datasource/issues/284#issuecomment-1192867502 solve your problem?

if not, could you describe your setup in more detail?

**Comment by anatoly-kor** [comment]
@gabor Yep, huge thanks for the help!
