### ISSUE TITLE
Grafana crashes when attempting to perform filter on json path

### ISSUE THREAD

**Issue by doanbutar** [grafana/grafana-json-datasource#285]
What happened?

Grafana crashes when attempting to use `?$filter` on the JSON API path

This occurs even when I’m not using the dashboard variable outside of the dashboard
When using Azure Monitor to perform the same, it Grafana converts the variable into the correct data for the Explorer view, how come doesn’t occur during this method?
What I’m seeing occur is as soon as I include the $ simple into my queries in Explore, Grafana breaks.

What was expected to happen?
Allow me to filter as part of the API request

Steps to reproduce the problem:

1. Either via Explore or Variable perform a query using JSON API data source
2. Set the path to /DesktopMachines?$
3. Site crashes with attachments

What is working?
Added `?`
```
<Grafana URL>/explore?orgId=1&left=%7B%22datasource%22:%22Pepper-CitrixCloud%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22cacheDurationSeconds%22:300,%22method%22:%22GET%22,%22queryParams%22:%22%22,%22urlPath%22:%22%2FSessionActivitySummaries%22,%22fields%22:%5B%7B%22jsonPath%22:%22$.value%22%7D%5D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D
```

What is not working?
Added `$`
```
<Grafana URL>/explore?orgId=1&left=%7B%22datasource%22:%22Pepper-CitrixCloud%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22cacheDurationSeconds%22:300,%22method%22:%22GET%22,%22queryParams%22:%22%22,%22urlPath%22:%22%2FSessionActivitySummaries%3F$%22,%22fields%22:%5B%7B%22jsonPath%22:%22$.value%22%7D%5D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D
```

As I’m trying to use `$filter` which works within the Dashboard and variable queries, it’s in Explore where it breaks. Even if I copy `/DesktopGroups?$filter=Name eq ‘Prod - Win2016 Silo NetSol - AUSYCTXVA3P`, which the qualified query for one of my variables, Explore still crashes.

Version numbers:
Grafana `9.0.2`
JSON API - `1.3.1`

**Comment by doanbutar** [comment]
I just tested and Explorer only crashes when the $ was being introduced, not when the URL construct is incorrect.

As per the below screenshot, the filter is not being introduced, that section is completely ignored and still returns valid data,
![image](https://user-images.githubusercontent.com/38452094/176314863-a7959653-215a-45d3-96bf-45d87c32cdfe.png)

Here is the expansion of one of the objects showing that the filter is not introduced as we are not calling it
![image](https://user-images.githubusercontent.com/38452094/176314905-955bb0b8-3497-4538-bb55-024d2b6ff5c9.png)

Here is an example of if the URL is incorrect and data doesn’t get returned.
![image](https://user-images.githubusercontent.com/38452094/176314937-fc7c7dae-3c22-4028-b8e8-fb915e20a187.png)

 I don’t think that is exactly happening here because if the plugin was thinking it was a variable, I would imagine this would occur in all areas of the product rather than just under the Explore context.
To add further, to the strangeness, when I run the following path below, it works fine

`/SessionActivitySummaries?$orderby=SummaryDate desc`
![image](https://user-images.githubusercontent.com/38452094/176315166-36a8ce7d-35da-4ab1-b942-bf753083fc82.png)

On further inspection as well, I noticed a strange even occurring when viewing the query history. As to why $orderby was working and it appears to be something relating to the data source occurring.


As you can see below, my query now works when running from query history
![image](https://user-images.githubusercontent.com/38452094/176315194-7f12f75e-cb73-4068-97e8-9eff63039172.png)


As you can see, it has introduced the azureMonitor data source for some reason?

Here are some of my queries I was running a while ago (still after the 13/6) as well, I think these are from when I use the explore option for the panel.
![image](https://user-images.githubusercontent.com/38452094/176315249-de03f8a5-965d-48e3-8526-5b9f339c2816.png)

Here are the queries on the 13/6 or before where I believe the issue was first occurring which seems to be resolved now as when I run the query from history, it works as expected.
![image](https://user-images.githubusercontent.com/38452094/176315279-de6133e7-c93f-44dd-99ef-6d3f6ab5ff5f.png)

**Comment by ollisco** [comment]
Have you tried adding your filter to the params instead of directly in the path

**Comment by gabor** [comment]
hi @doanbutar , did the solution proposed in https://github.com/grafana/grafana-json-datasource/issues/285#issuecomment-1196404115 solve your problem? if not , could you please try with the current grafana and plugin version and see if the problem still exists? thank you!

**Comment by doanbutar** [comment]
This seems to be a really old case. I haven't tried the solution proposed but since it's an old grafana version, the issue might no longer be there with the newest version. 

I am closing this issue and will reopen it if needed.
