### ISSUE TITLE
Question about Time on Grafana

### ISSUE THREAD

**Issue by ninijule** [grafana/grafana-json-datasource#292]
Hello, 

I'am using your plugin which is amazing first 👍 .
But I'm am facing a problem because i have to display huge amount of data.
### Exemple : I want to see the data from the last 6 hours, so i need to pass in my request from Grafana to my API the time i want. 
But i don't know how to specify in the request the time value.
![Grafana_Time](https://user-images.githubusercontent.com/27823056/179929547-5682db05-eabe-4896-8382-2ccaf540628f.PNG)

However, i figured out it's maybe possible to do this because it's possible by using the plugin InfluxDB which pass the time in request using "v.timeRangeStart, stop: v.timeRangeStop"
![image](https://user-images.githubusercontent.com/27823056/179929870-493067fc-a29f-448c-aa34-1df4f99a4fdc.png)

I use Grafana 9.0.0 in a Windows environement.
Thank you for the time you pass on this plugin !

**Comment by cton** [comment]
You can do that by using the macros as described in Documentation [Macros](https://marcus.se.net/grafana-json-datasource/macros)

**Comment by gabor** [comment]
hi @ninijule , it's as @cton described, use the variables described in https://marcus.se.net/grafana-json-datasource/macros
