### ISSUE TITLE
Teamviewer Api does not accept microsecond precision parameters

### ISSUE THREAD

**Issue by dpsenner** [grafana/grafana-json-datasource#301]
While attempting to fetch data from the Teamviewer endpoint https://webapi.teamviewer.com/api/v1/reports/devices it is currently not possible to filter with the parameters from_date and to_date because the parameters do not accept microsecond precision timestamps. This does mean that it is not possible to use the macros `$__isoFrom()` and `$__isoTo()` in this situation.

The api accepts the parameters `from_date` and `to_date` in the following format:

`from_date=2021-08-01T05:14:32Z`

This instead is generated by $__isoFrom():

`from_date=2021-08-01T05:14:32.442Z`

Please add macros that generate timestamps which:

1. Omit the subsecond fraction, i.e. `2021-08-01T05:14:32Z`
2. Are just plain dates without time component, i.e. `2021-08-01`

**Comment by Rablacan** [comment]
Hi!
Try use Grafana system variables to parameter, and string concatenate. ;) Its work for me
${__from:date:YYYY-MM-DDTHH}:${__from:date:mm}:${__from:date:ss}Z => 2022-08-27T07:07:12Z

**Comment by gabor** [comment]
hi @dpsenner , did @Rablacan 's solution work for you?

**Comment by gabor** [comment]
as we got no new information, we're closing the issue. we can reopen it if we get new info.
