### ISSUE TITLE
Update to latest JSONATA 1.8.6

### ISSUE THREAD

**Issue by ashishamway** [grafana/grafana-json-datasource#307]
I am getting error with JSONATA and it is likely with the underline version used for JSONATA.
Error says: _Key in object structure must evaluate to a string; got: undefined_
This error would not exist with version equal and above 1.8.6. Request you to please update to latest JSONATA.
You can check the input [here](https://www.stedi.com/jsonata/playground?statev2=eJztnFuPmkAUgP8KIT7sNrIg3lYfmtitTUz2Qlb70K4bMw5jlxRmDDP2ktX%2B9oLgKrSlXhgBd54Amcs5Z86cc%2FxEHh5kSmYuRHJZRj%2BmLqLUIti7AHNtXvGOz0MsSUPZMody2zs2qlUdwPEEVaqooTWqJhw3axqaDOVy0NBFkLjLxg%2F%2BB5L0HBz8eyZgKBhG13Rd0VqKrocdgwYIM9dCdKN3ZISgkYumJBilf99VbjpXivH%2BRhl0OzcbYwVNpy4xY4P9MWDQEgMnFM0h5sxGVDV%2FYsBcAFFs1KA9JDPM%2FA6VRvTmYvPycX2xKO%2BgUO%2FdnfLu7vZjXzE6n266t4O%2Bct817vjopzoEW4y4VH1ibKq8XI0BtWCy8lUOunduOwahzPCc8gnQuPWPs6ZNPnop%2FdmYQteaMm%2BP0Xv0Hbgm%2FYuC6BAd6dSe4a%2FqE4IKI18RTlb1MqZpeY8ZwXeq2sAZm0C1yRc6osxFwLHwl1Egy24SRGzNxd%2BBjVzmi%2BcNN7FsFF%2BCmICVFEyUxmZLVw5MmDWxIFi6Yug0CsEKBLbNX47dnDSNGQ9z0lRtnzxVjUPsueobSscwrntXnUHv7jbtkHOYbVt8EmjP4JgzkzXiVBJc9z50%2F6XTQeu3bVo8%2BsbXM9%2F4iRXO8T2rLmJvKrvJuOYZD4tm4cSUk6KTF80u8fCThucNjH5%2BU3HiVju9WjzbGngthzcfnNmAIXNEkfvNgmjkIOYe9wsBwMQBtuV9BmeUEUcNRBj55CcnpXFl21SwOg0%2FW8mUiKIqrcKjKB5fHQSKyhZFxSu%2BlPTKIYpKo7Y9LP0l2vr00p9AUUUsSo%2BYb3nE1FyjKE7gRqCotNUSKCpzFBUvNl9j7E1jNwkUlYWTF80uAkWddi0uUFSxUNS2P1quTnciUYV%2FKOo1gygekToHIIoTX8shh4prerq%2Fx%2BUk9wkOVcSK9IjJlkdIzTWH4pQ%2FM%2BRQPNKH4FD5%2ByqavWe9xtibxm4SHCoLJz8pu%2BzpeYJD5acWFxyqWBxq238qrU534VBavegcqsIjXBUFRPEoEnIAorZ%2BCLD4JCr7Wl88ESVIVO5r0mM%2Bgcwh9uSaRPF4%2FFSQKA5qiY2fOYlKI12f1BLsuZsEicrCyU%2FKLnt6niBR%2BanFBYkqFonaFrWsTlckyj8E7utNiRgwAQP%2BeKFsmxK9CODvXWBe%2BVPfIwdY2HNSv0nr8qUBsxw0IN0fU8td9r5sVC9bL3eh199b0Q6LEi%2B9OdCa7XqjXWteaFr1szclXoq4kMuy%2BiaQKfr2qvV7rv5rvCjFWDO4nTrW%2FtPvL2E8Mm8tavHNfz%2FuqUpdD4f0zCS9UYd4iM%2F86%2BBNYOEy%2BnSxLYUI8cIPTxf%2BDM9SqS2VlkOdlc7XzvHrrVRCAD6dTWYY%2BhHgrATLUgmfS8%2BbwpVwRJISlBaL83DJvKO3aGSuz6vzmvxYluvy42%2BGOIFG).

Can you please have a look and guide me how to get rid of it.

**Comment by pgillich** [comment]
I have same issue.
@marcusolsson Shall I create a pull request to upgrade JSONata version from 1.8.5 to 1.8.6? Will you have time to review it?
