### ISSUE TITLE
Allowed cookies does not work

### ISSUE THREAD

**Issue by ChamXE** [grafana/grafana-json-datasource#319]
I am using JSON API (Ver: 1.3.2) with Express.js to request data from the backend, the grafana_session cookie is needed for some processing. However, when using Grafana version 9.2.6, the allowed cookies are not included in the request.

I have used cookieParser so it shouldn't be an issue with my backend.
After testing, I figured out that from Grafana 9.1.8 until the latest version (9.3.1 for now), the allowed cookies function does not work.
Also tested with older versions (1.2.1, 1.3.0) of this plugin, it doesn't work either.

Below is an image of me printing out the cookies in the request, which you can see is null.

![image](https://user-images.githubusercontent.com/27875338/206596818-8e1ee027-4a57-47a2-91fd-4c59fd5c9f11.png)

**Comment by GuYounes** [comment]
I have the same issue here

**Comment by rvangsgaard** [comment]
I was looking into this, and I can confirm that possibility to pass the grafana_session cookie was removed here https://github.com/grafana/grafana/commit/4539c33fce5ef23badb08ebcbc09cb0cecb1f539

**Comment by gabor** [comment]
hi @ChamXE as others explained, this is not possible anymore, for security reasons.
