### ISSUE TITLE
Requests with params containing ":" character

### ISSUE THREAD

**Issue by JohnDuff44** [grafana/grafana-json-datasource#340]
Hello,

I would like to request an API but params require a ":" character.
Something like : /api/search?query=toto:chips+tata:bacon

In grafana, I've created the new source with the url /api/search
And when I create a new panel with params : 
```
key : query
value : toto:chips+tata:bacon
```
It doesn't work.

I also tried  : 
```
key : query
value : toto%3Achips+tata%3Abacon
```
But still doesn't work

Is there a way to make it work ?

Thanks
Have a good day,

**Comment by gabor** [comment]
hi @JohnDuff44 could you explain what does not work exactly? are you able to make the request with `curl` for example correctly?

**Comment by gabor** [comment]
as we got no new information, we're closing the issue. we can reopen it if we get new info.
