### ISSUE TITLE
Cannot see JSONAPI datasource in the plugin list

### ISSUE THREAD

**Issue by prashanthduvvada** [grafana/grafana-json-datasource#369]
After installing Grafana docker latest version, in the list of plugins, I'm unable to see the JSON API plugin.
![image](https://github.com/grafana/grafana-json-datasource/assets/20949342/78863239-3d05-4569-8aaa-ee9235b233cf)

Is there any error from the Grafana side or the plugin list?

**Comment by gwdawson** [comment]
@prashanthduvvada based on the screenshot provided it seems that you are searching through your "installed" plugins. if you set the state toggle to `All` you should see json-api there and be able to install it.
