### ISSUE TITLE
Suporte a paginação

### ISSUE THREAD

**Issue by ivanmirandaf** [grafana/grafana-json-datasource#378]
Olá,

Tenho um endpoit que lista o conteúdo de um determinado recurso e que se limita a 20 resultados. O restante se existir pode ser acessado com um parâmetro de consulta `?page=1` em uma nova requisição.

O plugin possui suporte a paginação ou teria outra maneira de listar o conteúdo até receber uma lista vazia (esse é o comportamento da API quando é feito uma requisição de uma página que não existe)?

**Comment by zoltanbedi** [comment]
Hi @ivanmirandaf,

No it is not supported. Your best bet here is to create multiple queires to see the results.
