### ISSUE TITLE
JSON API: Bad Gateway

### ISSUE THREAD

**Issue by mbarradas** [grafana/grafana-json-datasource#4]
While trying to connect to a WebService exposed from RapidMiner I get the JSON API: Bad Gateway error while configuring the data source.
I have tried with and without user credentials. Copying the headers sent by Postman and the error is the same. 
But the error is not helpful to understand what might be wrong.

**Comment by mbarradas** [comment]
I'm pasting the error I'm getting I guess the issue is related with the call being done through ip and not by the url of the process.

error="http: proxy error: dial tcp **ip:port**: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by marcusolsson** [comment]
@mbarradas Are you still experiencing this issue?

**Comment by DanielA2119** [comment]
Marcus,
I have a similar issue when attempting to connect to Azure for getting alert status information. First I get an error that API version is required, I add it to the headers section then I get a bad Gateway error. Could an example of a working connection to Azure using this DataSource plugin be provided?  Here is a link to Microsofts DOC on the what I am attempting to perform. https://docs.microsoft.com/en-us/rest/api/monitor/alertsmanagement/alerts/get-all.  Thanks.

**Comment by 0128zzc** [comment]
I meet the same question with you

**Comment by Christoper-Lloyd2** [comment]
I have also experienced the same issue as @AP-XD 

![image](https://github.com/grafana/grafana-json-datasource/assets/97893331/6c4cfc79-4871-4ad3-816d-39363e9c4a41)
![image](https://github.com/grafana/grafana-json-datasource/assets/97893331/f86590be-afe0-45ef-a2bc-25849a6f1fca)
Please note that the bad request in the second image is not my issue, it's simply because my endpoint does not return JSON at  the root URL, everything works fine with the datasource in the second image

**Comment by VictorZuluaga** [comment]
> Hello I just wanted to share that I also faced the similar issue while serving json file using localhost But when I use npoint.io for it it works fine. ![image](https://user-images.githubusercontent.com/63340491/228457913-f38fcefd-b440-4f23-8ebd-d644d1b10560.png) ![image](https://user-images.githubusercontent.com/63340491/228458080-f95c2d7d-56aa-47ec-8dc5-bb64ed2204e4.png)

Use your IPV4 instead of localhost, it worked for me

**Comment by AP-XD** [comment]
> > Hello I just wanted to share that I also faced the similar issue while serving json file using localhost But when I use npoint.io for it it works fine. ![image](https://user-images.githubusercontent.com/63340491/228457913-f38fcefd-b440-4f23-8ebd-d644d1b10560.png) ![image](https://user-images.githubusercontent.com/63340491/228458080-f95c2d7d-56aa-47ec-8dc5-bb64ed2204e4.png)
> 
> Use your IPV4 instead of localhost, it worked for me

Yeah I also used [npoint](https://www.npoint.io/) in the beginning but it was not a good solution for me to use ipv4 because I needed to serve some metrics which was being generated locally.
So actually what I did was create a **kubernetes service** for hosting the metrics locally which would be accessible by the **kubernetes environment** and thereby the grafana pod.
I needed it this way because other metrics were also being served to the grafana pod via **prometheus** which was also in kubernetes environment.

**Comment by AP-XD** [comment]
This issue can be closed I think @marcusolsson .
Since being unable to access localhost in environment other than kubernetes is a problem in grafana.
For which they have also provided a config `hostNetwork: true` in case if you want to access it though.

**Comment by zoltanbedi** [comment]
Thanks for coming back @AP-XD. I'm going to close this then.

**Comment by TomiwaAribisala-git** [comment]
> Hello I just wanted to share that I also faced the similar issue while serving json file using localhost But when I use npoint.io for it it works fine. ![image](https://user-images.githubusercontent.com/63340491/228457913-f38fcefd-b440-4f23-8ebd-d644d1b10560.png) ![image](https://user-images.githubusercontent.com/63340491/228458080-f95c2d7d-56aa-47ec-8dc5-bb64ed2204e4.png)


Hello, please I have a similar issue, I am running a Thanos Query Frontend locally and I want to add its URL in the datasource plugin, its giving JSON API: Bad Gateway, please how to I convert the URL:http://localhost:10901/ to npoint if it could work, I have attached images of the Datasource Plugin and Thanos URL
![datasource1](https://github.com/grafana/grafana-json-datasource/assets/109365443/cac08dca-b3e0-46d6-896b-6cab7bda29a5)
![datasource0](https://github.com/grafana/grafana-json-datasource/assets/109365443/e051c14e-724f-4f61-b02a-d81ffd66e45c)
![thanos](https://github.com/grafana/grafana-json-datasource/assets/109365443/82266aad-63c4-469c-b37d-56252259d6cb)
