### ISSUE TITLE
TimeShift not working

### ISSUE THREAD

**Issue by rkusniri** [grafana/grafana-json-datasource#420]
Hello

timeshift is not passed to plugin __from __to variables
reproduced : setting chart to last 8 days and making timeshift 1w  it will display last day only.
even in query inspector body sent using:
    "from": "${__from:date}",
    "to": "${__to:date}",
contain original not a timeshift date.
![json_api_issue_1](https://github.com/grafana/grafana-json-datasource/assets/118166883/1ae055c7-a530-4b72-90d3-117a8425e369)

GRAFANA 10.3.1
JSON API 1.3.6

**Comment by zoltanbedi** [comment]
duplicate of https://github.com/grafana/grafana-json-datasource/issues/245
