### ISSUE TITLE
Sharing dashboard is not allowed with this datasource

### ISSUE THREAD

**Issue by supportdesk-si** [grafana/grafana-json-datasource#434]
We completed design of the dashboard using the this data source and were trying to set it up for public viewing and got this message

Unsupported data sources
There are data sources in this dashboard that are unsupported for public dashboards. Panels that use these data sources may not function properly: marcusolsson-json-datasource.

[Read more about supported data sources](https://grafana.com/docs/grafana/next/dashboards/dashboard-public/)

What is the reason for this restriction?

Using latest version of Grafana and the plugin.

**Comment by zoltanbedi** [comment]
@supportdesk-si this data source is frontend only. The public(shared) dashboard feature is only available for data sources with backend. I suggest to use https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/ instead.
